<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [openssl-users] X509_verify_cert cannot be called twice
   </TITLE>
   <LINK REL="Index" HREF="https://mta.openssl.org/pipermail/openssl-users/2016-March/index.html" >
   <LINK REL="made" HREF="mailto:openssl-users%40openssl.org?Subject=Re%3A%20%5Bopenssl-users%5D%20X509_verify_cert%20cannot%20be%20called%20twice&In-Reply-To=%3C20160324203642.18296912.74642.59772%40ll.mit.edu%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="003411.html">
   <LINK REL="Next"  HREF="003413.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[openssl-users] X509_verify_cert cannot be called twice</H1>
    <B>Blumenthal, Uri - 0553 - MITLL</B> 
    <A HREF="mailto:openssl-users%40openssl.org?Subject=Re%3A%20%5Bopenssl-users%5D%20X509_verify_cert%20cannot%20be%20called%20twice&In-Reply-To=%3C20160324203642.18296912.74642.59772%40ll.mit.edu%3E"
       TITLE="[openssl-users] X509_verify_cert cannot be called twice">uri at ll.mit.edu
       </A><BR>
    <I>Thu Mar 24 20:36:34 UTC 2016</I>
    <P><UL>
        <LI>Previous message: <A HREF="003411.html">[openssl-users] X509_verify_cert cannot be called twice
</A></li>
        <LI>Next message: <A HREF="003413.html">[openssl-users] X509_verify_cert cannot be called twice
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#3412">[ date ]</a>
              <a href="thread.html#3412">[ thread ]</a>
              <a href="subject.html#3412">[ subject ]</a>
              <a href="author.html#3412">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I'm sure I'm missing something obvious, but why isn't the operation XXX_verify_xxx() idempotent? It seems very weird that two subsequent calls to verify() wouldn't return exactly the same thing.

Sent&#160;from&#160;my&#160;BlackBerry&#160;10&#160;smartphone&#160;on&#160;the Verizon&#160;Wireless&#160;4G&#160;LTE&#160;network.
&#160; Original Message &#160;
From: Szil&#225;rd Pfeiffer
Sent: Thursday, March 24, 2016 16:21
To: <A HREF="../../../mailman/listinfo/openssl-users.html">openssl-users at openssl.org</A>
Reply To: <A HREF="../../../mailman/listinfo/openssl-users.html">openssl-users at openssl.org</A>
Subject: Re: [openssl-users] X509_verify_cert cannot be called twice

On 2016-03-24 19:12, Viktor Dukhovni wrote:
&gt;&gt;<i> On Mar 24, 2016, at 2:02 PM, DEXTER &lt;<A HREF="../../../mailman/listinfo/openssl-users.html">mydexterid at gmail.com</A>&gt; wrote:
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> So let me get this straight.
</I>&gt;&gt;<i> If someone had a software where they called X509_verify_cert from
</I>&gt;&gt;<i> SSL_CTX_set_cert_verify_callback callback twice (to verify first with
</I>&gt;&gt;<i> crls, and maybe verify again without crls) and it worked as expected,
</I>&gt;&gt;<i> after this patch their software is broken.
</I>&gt;<i> 
</I>&gt;<i> If they re-used the same X509_STORE_CTX, yes their software depended
</I>&gt;<i> on undefined and likely insecure behaviour. &quot;Worked as expected&quot; is
</I>&gt;<i> likely more along the lines of &quot;did not appear to fail&quot;. Verification
</I>&gt;<i> is not only expected to succeed for valid chains, but is also expected
</I>&gt;<i> to reliably fail for invalid chains.
</I>&gt;<i> 
</I>
You are absolutely right in your last sentence, but an application which 
should have expected (before the patch) that it does not get the error 
code ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, as it was permitted (according 
to the documentation) to call the X509_verify_cert more than once. IMHO 
an API compatible fix (1.0.1p was a security update) should consider 
this, otherwise the undefined behavior shifted from the library to the 
application.

The problem what I try to explain is not just a theory. Consider the 
situation when a function in an application tries to verify a 
certificate by calling X509_verify_cert twice with different parameters 
(it is a questionable, but a permitted way) during the handshake. It 
works very well before the patch. After the patch the second call 
returns error, so the function also returns error and the SSL handshake 
fails. So a security update contains the patch breaks the application.

Szil&#225;rd




-- 
openssl-users mailing list
To unsubscribe: <A HREF="../../../mailman/listinfo/openssl-users.html">https://mta.openssl.org/mailman/listinfo/openssl-users</A>

-------------- next part --------------
A non-text attachment was scrubbed...
Name: smime.p7s
Type: application/x-pkcs7-signature
Size: 4350 bytes
Desc: not available
URL: &lt;<A HREF="http://mta.openssl.org/pipermail/openssl-users/attachments/20160324/d9b6ca65/attachment.bin">http://mta.openssl.org/pipermail/openssl-users/attachments/20160324/d9b6ca65/attachment.bin</A>&gt;
</PRE>






<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="003411.html">[openssl-users] X509_verify_cert cannot be called twice
</A></li>
	<LI>Next message: <A HREF="003413.html">[openssl-users] X509_verify_cert cannot be called twice
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#3412">[ date ]</a>
              <a href="thread.html#3412">[ thread ]</a>
              <a href="subject.html#3412">[ subject ]</a>
              <a href="author.html#3412">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="../../../mailman/listinfo/openssl-users.html">More information about the openssl-users
mailing list</a><br>
</body></html>
