<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> SSL_read() returning SSL_ERROR_SYSCALL with errno 11 EAGAIN
   </TITLE>
   <LINK REL="Index" HREF="https://mta.openssl.org/pipermail/openssl-users/2019-May/index.html" >
   <LINK REL="made" HREF="mailto:openssl-users%40openssl.org?Subject=Re%3A%20SSL_read%28%29%20returning%20SSL_ERROR_SYSCALL%20with%20errno%2011%20EAGAIN&In-Reply-To=%3CDM6PR07MB4650860A674F2A60EFC99E96F53B0%40DM6PR07MB4650.namprd07.prod.outlook.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="010369.html">
   <LINK REL="Next"  HREF="010371.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>SSL_read() returning SSL_ERROR_SYSCALL with errno 11 EAGAIN</H1>
    <B>John Unsworth</B> 
    <A HREF="mailto:openssl-users%40openssl.org?Subject=Re%3A%20SSL_read%28%29%20returning%20SSL_ERROR_SYSCALL%20with%20errno%2011%20EAGAIN&In-Reply-To=%3CDM6PR07MB4650860A674F2A60EFC99E96F53B0%40DM6PR07MB4650.namprd07.prod.outlook.com%3E"
       TITLE="SSL_read() returning SSL_ERROR_SYSCALL with errno 11 EAGAIN">John.Unsworth at synchronoss.com
       </A><BR>
    <I>Wed May  1 13:47:33 UTC 2019</I>
    <P><UL>
        <LI>Previous message: <A HREF="010369.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11 EAGAIN
</A></li>
        <LI>Next message: <A HREF="010371.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11 EAGAIN
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10370">[ date ]</a>
              <a href="thread.html#10370">[ thread ]</a>
              <a href="subject.html#10370">[ subject ]</a>
              <a href="author.html#10370">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>This is what we do:

Create a non-blocking TCP socket.
Call SSL_new(), SSL_set_fd(), SSL_connect()
Thereafter call SSL_read().
Renegotiates handled by OpenSSL.

We have only seen the error very occasionally, the vast majority of calls return SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE.
The following is traced when we get the fail, originally we then caused a disconnect but now handle it as discussed:

LDAP: session=7F38AE82F840 socket read error SSL Error Syscall: LastError 11

Note that because our code automatically reconnects and reissues failed and aborted operations customers would not normally see the error. In this case though we disconnected while a modify operation was running in the LDAP server, after reconnecting the modify was reissued and failed because of attribute deletion by the original modify. The investigation showed up the error. The customer was running a soak test and thousands (maybe millions) of reads worked fine until the failing one.

Regards,
John.

-----Original Message-----
From: openssl-users &lt;<A HREF="../../../mailman/listinfo/openssl-users.html">openssl-users-bounces at openssl.org</A>&gt; On Behalf Of Erik Forsberg
Sent: 01 May 2019 03:05
To: <A HREF="../../../mailman/listinfo/openssl-users.html">openssl-users at openssl.org</A>
Subject: Re: SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN

CAUTION: This email originated from outside of Synchronoss.


&gt;<i>-- Original Message --
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;&gt;<i>-- Original Message --
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>On Tue, Apr 30, 2019 at 03:23:23PM -0700, Erik Forsberg wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> &gt;Is the handshake explicit, or does the application just call 
</I>&gt;&gt;&gt;<i> &gt;SSL_read(), with OpenSSL performing the handshake as needed?
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> I occasionally (somewhat rarely) see the issue mentioned by the OP.
</I>&gt;&gt;&gt;<i> Ignoring the error, or mapping it and do what WANT_READ/WANT_WRITE 
</I>&gt;&gt;&gt;<i> does effectively hides the issue and connection works fine. I 
</I>&gt;&gt;&gt;<i> predominantly run on Solaris 11. In my case, I open the socket 
</I>&gt;&gt;&gt;<i> myself, set non-blocking mode and associates with an SSL object using SS_set_fd().
</I>&gt;&gt;&gt;<i> The initial handshake is done explicitly.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>Recoverable errors should not result in SSL_ERROR_SYSCALL.  This feels 
</I>&gt;&gt;<i>like a bug.  I'd like to hear from Matt Caswell on this one.
</I>&gt;&gt;<i>Perhaps someone should open an issue on Github...
</I>&gt;&gt;<i>
</I>&gt;<i>I will scan my logs later this evening and see if this is still an issue.
</I>&gt;<i>Last time I remember seeing it was quote some long time ago (couple of 
</I>&gt;<i>years)
</I>&gt;<i>
</I>&gt;<i>
</I>
ok, I checked my logs (3+ years worth of them) and I have not seen this error in that timeframe.
so it must have been a much older OpenSSL version I used way back when I remember doing this workaround.
Doesnt seem to be needed for me anymore.


</PRE>



<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="010369.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11 EAGAIN
</A></li>
	<LI>Next message: <A HREF="010371.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11 EAGAIN
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10370">[ date ]</a>
              <a href="thread.html#10370">[ thread ]</a>
              <a href="subject.html#10370">[ subject ]</a>
              <a href="author.html#10370">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="../../../mailman/listinfo/openssl-users.html">More information about the openssl-users
mailing list</a><br>
</body></html>
